### PR TITLE
Segregated routes

### PR DESCRIPTION
**Pull request by bucko13**
This PR closes the loop on the initial MVP for LSAT enabled paywalls on meme server uploads. Using this update, a meme server admin can enable paywalls for large uploads by running this alongside an aperture-enabled sphinx stack and then setting the environment variables `RESTRICT_UPLOAD_SIZE` and (optionally) `MAX_FREE_UPLOAD_SIZE_MB`. 

Once this is running, any uploads to `/file` that have files that are larger than `MAX_FREE_UPLOAD_SIZE_MB` (or the default of 1MB) will be rejected as too large. To upload larger files, clients can upload to `/largefile`. Aperture will reject the initial attempt with a `402 Payment Required`. Paying the invoice and satisfying the LSAT will allow larger uploads (up to 32MB as dictated by the aperture configs that mint the LSAT) via `/largefile`. 

Two outstanding questions I had and could use feedback on:
1. I started with MBs as the base unit because it was being used in other places, but I'm wondering if a smaller unit might be better for more granularity. KB? Bytes? 
2. there's a file `size.go` that has a middleware that sets the file size restrictions in a context key that is then used in the main uploadFile function. I wasn't sure if that was better as a middleware or some kind of utility function so I'm open to refactoring that. 

More details on how it works and how to play around with it are in the updated README in this PR.

### CODE REVIEW

**Comment by Evanfeenstra** [comment]
nice @bucko13 !

1. TBH i think MB is fine... storage is just getting cheaper and cheaper anyway. MB is just easy to think in terms of.

2. I think its fine as a middleware. The one thing I don't like is the `if !strings.Contains(path, "file")` line... better to segregate routes with a separate `r.Group` in router.go. Its a bit more verbose but more obvious whats going on

**Comment by bucko13** [comment]
> I think its fine as a middleware. The one thing I don't like is the if !strings.Contains(path, "file") line... better to segregate routes with a separate r.Group in router.go. Its a bit more verbose but more obvious whats going on

Ah ok. Yeah I actually do have them each in two groups and the idea was I wanted to use the same middleware but respond slightly differently depending on the route. It wasn't clear if a parameter could be passed to middleware which I think would make that the cleanest, but maybe I just split it up into two middleware then.

**Comment by bucko13** [comment]
@Evanfeenstra Actually, there are two lines that do that filtering. One checks for `file` and the other checks for `largefile`. The middleware is already used in groupings, one that's the default `/file` path (and I added the first as a "just in case" guard, but it probably could go) and the other in the `/largefile`. The second `match` check is to see which of the two paths it's in and set the context accordingly.  The ideal would be if an argument could be passed to the middleware but I couldn't see any good examples of that anywhere.

If it was just the first check you didn't like, I'll remove that and leave the rest the same (I don't think it'll impact the normal get media paths anyway that exist in the first grouping). If you think it's best to remove both I can split it up into two middlewares (maybe a third that runs in both cases to avoid duplicating some of the logic)?

**Comment by Evanfeenstra** [comment]
@bucko13 just noticed a thing... you have both `MaxUploadSizeContextKey` and `MaxUploadContextKey` in there.

Although it wont impact the logic of get media routes, still it will impact performance a little bit. Since all files are downloaded here (like every user avatar in a chat), these can be hit tons of times a second, so I would prefer to not add any extra parsing of env or whatever to the get media routes. Its fine to make a whole new r.Group that repeats a lot of the middlewares just for the /file route.

Also you can kinda pass a param to a middleware by making a third util function:

```
func GetMaxUploadSizeContext(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	        doTheThing(w, r, false)
	}
}

func GetLargeMaxUploadSizeContext(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	        doTheThing(w, r, true)
	}
}

func doTheThing(w http.ResponseWriter, r *http.Request, largefile bool) {
  // do the thing
}
```

**Comment by Evanfeenstra** [comment]
or just a URL param `?large=true` maybe? Anyway not a huge deal! Either way this is awesome

**Comment by bucko13** [comment]
> or just a URL param ?large=true maybe?

Unfortunately the query parameter option won't work until we decide we want _all_ uploads to require an LSAT (and then the level of your lsat will determine how much you can upload). Because the requests are filtered via a kind of "negative whitelist" by aperture, anything that matches the target of the filter by path will require an LSAT. That's why I made a whole separate path for the large uploads, but then also wanted to make sure using the old path wouldn't be a way to get around the paywall. Definitely added some complexity, but for understandable reasons! 

I'll play around with splitting things up a bit and see what I can come up with.

**Comment by bucko13** [comment]
Thanks for the suggestions @Evanfeenstra! 

I think I've got some good changes as a result

- I split up the GET and POST groupings for `/file` so that the `GET` doesn't have the lsat context interactions [ffbb1cb](https://github.com/stakwork/sphinx-meme/pull/9/commits/ffbb1cb1de863aed55f45a8d2d0eeb66793ee691)
- I got reused the existing max size context key for the lsat rather than have two very similar ones. There was no reason to have two, just override the existing one based on env vars and taking the original into account. ([63ceb83](https://github.com/stakwork/sphinx-meme/pull/9/commits/63ceb83ebd5f82a0cd5198cfd772fd8a6f25bbbe))
- I used your suggestion to have two separate middelwares that call the same function and pass it a bool ([58f7a99](https://github.com/stakwork/sphinx-meme/pull/9/commits/58f7a99f06a905e182d3f28ac47c594f2648fc54)). The only thing I changed from your snippet was that I also needed to pass in `next`, but otherwise everything else worked as is.

**Comment by Evanfeenstra** [comment]
beautiful! Thanks @bucko13 !

**Pull request merged**
